### PR TITLE
Modern UI changes to chatApp

### PR DESCRIPTION
**Pull request by abhikrishnaram**
image
updated v2
image

### CODE REVIEW

**Comment by osBins** [comment]
Looks great @abhikrishnaram! Good work.
Can you create an issue for this so that workflow in the repository can be streamlined? I'll link this PR to that issue so that it looks more organized.
I'll check your changes out locally after that's done and merge the PR if everything's working fine.

**Comment by abhikrishnaram** [comment]
Related to issue #118

**Comment by osBins** [comment]
Neat work @abhikrishnaram! There are a few changes that need to be made though - 
1. Really long usernames are flowing out of the container where current user's username and email ID are showing  
image
2. Can this outline be removed? It comes on clicking and selecting the 'Type a message' input box.  
image
3. Can you look into this icon which isn't showing up? Can you remove it or put a message callout sort of icon in it's place? Whatever looks and feels better to you.
image
4. Chrome and Firefox are differing on the CSS for the message boxes. On Firefox, there is a gap between the box and the small triangle (crimp) on its side (both blue and grey ones). Can you look into this too?  
Chrome -  
image  
Firefox -  
image  

Also, there's a bug in sending images where image shows up on the left side even when current user is sending it  
image  
But I believe this can be fixed in another issue.

**Comment by abhikrishnaram** [comment]
I was not able to reproduce 4th error. 5th one i hope you can fix via another issue @osBins. Rest has been fixed.

**Comment by osBins** [comment]
Looks neat. Nicely done @abhikrishnaram. I'll open separate issues for the 4th bulleted point and the bug I mentioned in the end. Merging your PR.

**Pull request merged**
