### PR TITLE
Fixed Reset Password Page

### PR DESCRIPTION
**Pull request by snahashisk**
Fixed issue #146 
Please review it @osBins 
fapage

### CODE REVIEW

**Comment by osBins** [comment]
Hey @snahashisk, what's the change in `old.main.css` for? Is it being used anywhere?

**Comment by snahashisk** [comment]
Ig prettier fixed indentation in old.main.css.

**Comment by PrimalPimmy** [comment]
Hey @snahashisk , there's a font inconsistency, can you please look into it? Screenshot comparison:
image

**Comment by snahashisk** [comment]
Okay I'll fix that.

**Comment by snahashisk** [comment]
Fixed that issue. 
chromeFix
mozillaFix2
Used 2 different browser getting same result.

**Comment by PrimalPimmy** [comment]
Looks good to me 🚀

**Pull request merged**
