### PR TITLE
Updated login sign up page design 

### PR DESCRIPTION
**Pull request by snahashisk**
Fixed Issue #103 
signup
login

Please review it @osBins

### CODE REVIEW

**Comment by osBins** [comment]
@snahashisk there are merge conflicts with public/main.css right now. Can you resolve them? I'll check out your PR and merge your changes after testing them.

**Comment by osBins** [comment]
Looks good for now. Have you used a template for this? If that's the case, can you tell me where it's from?

**Comment by snahashisk** [comment]
> Looks good for now. Have you used a template for this? If that's the case, can you tell me where it's from?

I haven't used any temple. I got this design idea from Pinterest.

**Comment by osBins** [comment]
Oh right, and where's the image on the left from?

**Comment by snahashisk** [comment]
It was from freepik. If you r thinking about copyright issues I can draw a vector illustration like that too. And then I'll change that.

**Comment by osBins** [comment]
Oh, it's alright since its freepik. Great work @snahashisk! Merging your PR

**Pull request merged**
