### PR TITLE
Scroll screen at bottom (even when "is typing..." appears)

### PR DESCRIPTION
**Pull request by jaiakash**
It was mentioned to send PR as soon as  i start working. So this is the pr. I would be committing to this branch in future for issue #31

### CODE REVIEW

**Comment by osBins** [comment]
Great. Also, please note that commits made only after the coding period has started count for KWoC^^

**Comment by jaiakash** [comment]
For this issue, it was asked to add auto-scroll when messages fill the entire screen.
But this feature is already present, when messages fills the entire screen, the scroll automatically moves down.

**Comment by osBins** [comment]
Right, could you make some changes to show new messages being added to the bottom, instead of being appended from the top then?

**Comment by jaiakash** [comment]
I didnt get you. Even with current version, the new messages are added to bottom and top most messages moves up. Is that what you are asking?

**Comment by osBins** [comment]
Right so, if we take WhatsApp, or Discord for example, when we send a new message, they're placed right above the input message field and on subsequent new text messages, the previous ones move up and new ones are added in the same place, above the input message field

**Comment by jaiakash** [comment]
Ha, I understood what you are asking me to add.

But isnt this feature already there? When i run the current chatapp version, the new messages are added just above the input box while the previous messages moves up!

**Comment by osBins** [comment]
image
Currently they're added to the top, just below the 'online' users list. They red arrow shows where they should preferably placed^^
Let me know if there's still a problem in understanding

**Comment by jaiakash** [comment]
Ya got it now ;)
I am working on it now.

**Comment by osBins** [comment]
Great! I'll merge your PR when the coding period starts then!

**Comment by osBins** [comment]
@jaiakash since this issue is no longer valid because we have a completely different design now, can you work on fixing the "<user> is typing..." message? It doesn't scroll down when the 'user is typing' message comes, and only when a new message is received.

**Comment by jaiakash** [comment]
> @jaiakash since this issue is no longer valid because we have a completely different design now
Yeah, the interface has changed a lot from last time. Actually, I was busy with my semester exams :) 

> can you work on fixing the " is typing..." message?
Pushed the changes, now screen scroll even when "is typing.." messages come.

**Comment by osBins** [comment]
Sounds good. I hope your exams went well!
I'll check out your changes. Till then, can you change the title of the PR to state the issue you've fixed?

**Comment by osBins** [comment]
Good work @jaiakash! Merging your PR.

**Comment by jaiakash** [comment]
closes #31

**Pull request merged**
