### PR TITLE
Image sending bug fixed

### PR DESCRIPTION
**Pull request by Shreya-Agrawal-2121**
Earlier on sending image it was appearing on left even for the user sending it. Now this issue is resolved

### CODE REVIEW

**Comment by PrimalPimmy** [comment]
can you send a screenshot that it is working properly?

**Comment by Shreya-Agrawal-2121** [comment]
Screenshot 2022-01-02 225327.png
<https://drive.google.com/file/d/1_f3slhabwN74ZREiJZ1yWDB_6C6Kfb34/view?usp=drivesdk>

**Comment by PrimalPimmy** [comment]
Shows access denied, you can also just drag the image here by the way, github uploads it

**Comment by Shreya-Agrawal-2121** [comment]
Okay will do that

**Comment by Shreya-Agrawal-2121** [comment]
image

**Pull request merged**
