### PR TITLE
add Search Box

### LINKED ISSUE #66: Implementing "search in chat" feature
@osBins please assign me this issue

### PR DESCRIPTION
**Pull request by sushovanb02**
Fixes #66
@PrimalPimmy @osBins please review

### CODE REVIEW

**Comment by PrimalPimmy** [comment]
Hey, can you show us a video for it's working? Post it here, then only I could review it.

**Comment by sushovanb02** [comment]
https://user-images.githubusercontent.com/73771796/145444924-f133959a-365a-466e-985a-a3f7d2b131e3.mp4

@PrimalPimmy here is the video

**Comment by PrimalPimmy** [comment]
Great work! There seems to be some merge conflicts, can you try to fix those? Make sure it doesn't break other functionality of the app. Rest LGTM :rocket:

**Comment by sushovanb02** [comment]
conflicts resolved!! @PrimalPimmy @osBins

**Comment by osBins** [comment]
Hey @sushovanb02, great work on the 'search' functionality. However, your PR seems to be breaking these two features-
1. Markdown syntax rendering 
2. Change of 'send' button colour on pressing 'Enter'/mouse down  

For Markdown rendering -   
image

For 'send' button -   
image
  
image

Can you compare the changes in client.js with upstream repository and add these features back?

**Comment by sushovanb02** [comment]
> Hey @sushovanb02, great work on the 'search' functionality. However, your PR seems to be breaking these two features-
> 
> 1. Markdown syntax rendering
> 2. Change of 'send' button colour on pressing 'Enter'/mouse down
> 
> For Markdown rendering - image
> 
> For 'send' button - image
> 
> image
> 
> Can you compare the changes in client.js with upstream repository and add these features back?

Sure! will try tomorrow

**Comment by sushovanb02** [comment]
@osBins all changes done as requested

**Comment by osBins** [comment]
Nicely done @sushovanb02! Merging your PR.

**Comment by vedantiitkgp** [comment]
Search box UI is buggy

**Comment by vedantiitkgp** [comment]
Please unmerge and test this commit @osBins

**Comment by osBins** [comment]
> Search box UI is buggy

Can you explain what the bug exactly is?

**Comment by vedantiitkgp** [comment]
https://user-images.githubusercontent.com/32813089/145680479-2efc2c74-5aaa-4a28-b34b-49b24d415528.mp4


messes up the message I am sending also search box is buggy which is the commit that caused the problem @osBins

**Comment by sushovanb02** [comment]
https://user-images.githubusercontent.com/73771796/145681260-f85dea03-e0db-48bb-8929-d1e98334dc38.mp4

@vedantiitkgp @osBins actuallly it was working perfectly here so I thought it has no problem

**Comment by sushovanb02** [comment]
@vedantiitkgp when I'm opening it in website it is working perfectly for me so I'm unable to understand

**Pull request merged**
