### PR TITLE
updated the send button

### PR DESCRIPTION
**Pull request by snahashisk**
fixed issue #48 
fixed some indentation

### CODE REVIEW

**Comment by osBins** [comment]
Hey @snahashisk. Can you attach a screenshot to show the changes you've made?

**Comment by snahashisk** [comment]
chat--btn-red
this is the permanent state of the button

chat--btn-green
on mouse down event it'll be like this and then it'll go back to its previous state (the red one). 

also fixed some indentations.

**Comment by osBins** [comment]
Can you add a little timeout to the 'sent' state of button? It's changing back to red very quickly.

**Comment by osBins** [comment]
Also, can you add some code to prevent the button from changing to green when the input text message is empty? It says 'sent' even when nothing is being sent

**Comment by snahashisk** [comment]
Did all the necessary changes. added 400ms timeout and btn is unclickable if the input is empty.

**Comment by osBins** [comment]
Nicely done @snahashisk! Merging your PR.

**Pull request merged**
