### PR TITLE
new design changes

### PR DESCRIPTION
**Pull request by vedantiitkgp**

### CODE REVIEW

**Comment by osBins** [comment]
That is great work @vedantiitkgp! The different colours for different users look amazing and I love the notification sound along with other little nitty-gritties which you have taken care of! There are a few changes I have to request though, after which your Pull Request will be ready to merge.
1. Can you make the roundness of the 'Username' and 'Text message' input fields same for a consistent design?
2. The border on the 'username' field and the outline on 'online' users button after clicking it, look a little weird. Can you edit the CSS to remove the border and outline on them?
3. The red border around the chat messages div looks way too prominent. Can you make it thinner and change to a subtle colour?
4. Also if possible, can you stylize the scrollbar inside the chat-message div on content overflow? The default scrollbar doesn't look that great and I'm sure you can come up with something which looks way cooler.
5. Can the title on the page be made smaller? I believe it is taking too much space and doesn't leave much space for the actual chat-messages content.
6. In `client.js` can you edit out the timestamp code around line 106-117, and make the relevant changes on line 119 to just show the username and text message (since someone is already working on the timestamp issue). I'll merge the other online users list PR temporarily, and we can go forward with your final one once you are done making the requested changes^^

Let me know if there's an issue with any of these. Thank you for your work!

**Comment by vedantiitkgp** [comment]
ScreenShots

Screenshot 2021-12-06 at 4 35 35 PM

Updated the Online Panel

Screenshot 2021-12-07 at 4 14 13 AM

**Comment by vedantiitkgp** [comment]
Close this request as soon as possible for other to work with this new design @osBins

**Comment by osBins** [comment]
Awesome! The new frontend looks really good. Merging your PR @vedantiitkgp.

**Pull request merged**
