### PR TITLE
Updated Search box

### PR DESCRIPTION
**Pull request by SachinMittal1766**
@PrimalPimmy @osBins I have updated CSS of search box.

### CODE REVIEW

**Comment by osBins** [comment]
Looks nice @SachinMittal1766! Can you make the placeholder say "Search..." with three dots instead of two, like it is right now (it's somewhat of a convention).
Also, can you remove the border and outline (on click) and add a similar border as the messages container to the 'search' box?
The border radius looks fine.

**Comment by osBins** [comment]
Going good so far @SachinMittal1766! Can you make the remaining changes and pull changes from the main branch to update your repository? It seems to be behind by a few commits.

**Comment by osBins** [comment]
Looks good to me now! However there's still a border/outline coming on clicking the search box. Can you remove that?

**Comment by SachinMittal1766** [comment]
@osBins completed all the updates.

**Comment by osBins** [comment]
Awesome! Merging your PR.

**Pull request merged**
