### PR TITLE
Improve README.md 

### PR DESCRIPTION
**Pull request by jaiakash**
I have added this PR for issue #45 
In the first commit, I have added 3 screenshots of app.

For future commits, please clarify
1. Do we really need images for contribution on main readme file of project. We can have a simple code based contribution section and remove the images of fork, git clone. Something like this [firstcontribution](https://github.com/firstcontributions/first-contributions/blob/master/README.md#clone-the-repository)
2. Similary for installing MongoDB, do we need a section on main readme file. We can add links on external websites for installing mongodb.

### CODE REVIEW

**Comment by osBins** [comment]
1. That's a fine idea. The images were initially included to be targeted at beginner level contributors. The link you provided looks much better and cleaner without images all over the place. Do what looks good to you and I'll review it.
2. Again, they're included to be targeted at people who are new to development and might need guidance installing and setting up a database. If you find good resources to link, by all means, feel free to remove the section and include links in its place.

**Comment by osBins** [comment]
Hey @jaiakash, as much as this looks good, it seems to be extremely similar to the [firstcontribution](https://github.com/firstcontributions/first-contributions/blob/master/README.md#clone-the-repository) link you posted above. 
I would appreciate a few changes (be it paraphrasing, or including screenshots of your own instead of the ones used in the other repository as it is). 
Also revamping the 'Contributions' section because it guides beginners to add their name to a 'Contributing.md' file, which is not the case when one is contributing to the chatApp. 
There's no need to include instructions from forking to pushing and creating a pull request, just forking and cloning should do. Resources for learning how to commit and push changes, and opening PRs can be linked to resources you find good.

**Comment by osBins** [comment]
@jaiakash let me know if you're still working on this by tonight

**Comment by jaiakash** [comment]
Can you please assign this issue to someone else. I have some personal engagement to attend. Hope it's fine.

**Comment by osBins** [comment]
That's alright, thank you for letting me know!

**Pull request closed without merging**
