### PR TITLE
Implemented personal messaging feature

### PR DESCRIPTION
**Pull request by cp-Coder**
Fixed issue #5. Also, there may be some formatting changes in the file.

### CODE REVIEW

**Comment by vedantiitkgp** [comment]
Hey, @cp-Coder just a suggestion please refrain from adding spaces and semicolons unnecessarily in the codebase will cause difficulty reviewing your commits

**Comment by PrimalPimmy** [comment]
I think that might be due to vscode or any other IDE automatically formatting and adding semi-colons

**Comment by osBins** [comment]
@cp-Coder can you pull changes from the main upstream branch and rebase? There are merge conflicts which need to be resolved.

**Comment by cp-Coder** [comment]
I have resolved all the conflicts

**Comment by osBins** [comment]
Hey @cp-Coder, your 'main' branch is still 3 commits behind the main branch of the upstream repo. Can you rebase with the upstream repository so that your branch is up to date?

**Comment by cp-Coder** [comment]
My branch has been updated.

**Comment by cp-Coder** [comment]
I have created another pull request and made all the changes. This time there won't be any conflicts.

**Pull request closed without merging**
