### PR TITLE
improve username, 'Type a message...' input field 

### LINKED ISSUE #52: improve username, 'Type a message...' input field
like this.......

### PR DESCRIPTION
**Pull request by kuldeepsingh0330**
fix #52

### CODE REVIEW

**Comment by osBins** [comment]
Hey @kuldeepsingh0330, can you attach a screenshot to show what your changes look like now?

**Comment by kuldeepsingh0330** [comment]
Screenshot 2021-12-06 193645

**Comment by osBins** [comment]
@kuldeepsingh0330 good work. Could you center the 'username' placeholder for now? I'll merge your PR as soon as that's done.

**Comment by osBins** [comment]
@kuldeepsingh0330 if you're still working on this, can you refork again like I mentioned in the other Pull Request and then edit the code in the same way?

**Pull request closed without merging**
