### PR TITLE
Fix space on right side of screen

### PR DESCRIPTION
**Pull request by amm98d**
The problem was in the #header nav CSS. I have implemented a fix for now. 
However, for a more responsive and general solution, flexbox should be added to the whole website.

### CODE REVIEW

**Comment by osBins** [comment]
That was resolved quickly! Good work @amm98d. Can you attach a screenshot of the chatApp UI so that I can have a look at the change?

**Comment by amm98d** [comment]
> That was resolved quickly! Good work @amm98d. Can you attach a screenshot of the chatApp UI so that I can have a look at the change?

Sure thing, here you go:

image

**Comment by osBins** [comment]
Can you have a look at the online users list @amm98d? I just checked out your PR locally and the online users list seems to have gotten slightly messed in the process. Can you rectify that?

**Comment by amm98d** [comment]
> Can you have a look at the online users list @amm98d? I just checked out your PR locally and the online users list seems to have gotten slightly messed in the process. Can you rectify that?

Got it, fix coming up shortly.

**Comment by amm98d** [comment]
@osBins update pushed. Feel free to let me know if anything missing :)

**Comment by PrimalPimmy** [comment]
@amm98d can you git pull and rebase on your side, since we removed pockage-lock and it's causing a merge conflict. Please resolve it

**Comment by amm98d** [comment]
> @amm98d can you git pull and rebase on your side, since we removed pockage-lock and it's causing a merge conflict. Please resolve it

Sure thing

**Comment by osBins** [comment]
@amm98d since you suggested that flexbox be added to the whole site, would you be willing to work on it?

**Comment by amm98d** [comment]
> @amm98d since you suggested that flexbox be added to the whole site, would you be willing to work on it?

Sure, I'll open a PR with a new branch.

**Pull request merged**
