### PR TITLE
database storage implemented

### PR DESCRIPTION
**Pull request by ankitgarg1234**
database storage implemented #43

### CODE REVIEW

**Comment by osBins** [comment]
Whew, merge conflicts resolved. Will go through this one more time tomorrow and then finally merge it.

**Comment by ankitgarg1234** [comment]
okay

**Comment by ankitgarg1234** [comment]
created sign up and login form #39

**Review by PrimalPimmy — APPROVED** [review]

**Comment by osBins** [comment]
Great work on the database @ankitgarg1234! Merging your PR.

**Comment by osBins** [comment]
Welp, something broke. We're looking into it

**Comment by osBins** [comment]
@ankitgarg1234 we're experiencing two bugs right now.
1. When logged in from two different systems, if one page is refreshed, it takes the session of the other person who is logged in (checked out both locally and on deployment)
2. When browser is closed and opened again to localhost, it is already logged in but when you send a message, it's sent from an 'undefined' username, after which the server crashes.
```{ id: '61b479d091ab48251823ea10', iat: 1639217622, exp: 1639476822 }
A user has connected
Received a chat message
undefined
D:\git\chatApp\node_modules\mongoose\lib\document.js:2913
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: message validation failed: email: Path `email` is required.
    at model.Document.invalidate (D:\git\chatApp\node_modules\mongoose\lib\document.js:2913:32)
    at D:\git\chatApp\node_modules\mongoose\lib\document.js:2704:17
    at D:\git\chatApp\node_modules\mongoose\lib\schematype.js:1280:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errors: {
    email: ValidatorError: Path `email` is required.
        at validate (D:\git\chatApp\node_modules\mongoose\lib\schematype.js:1277:13)
        at D:\git\chatApp\node_modules\mongoose\lib\schematype.js:1260:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (D:\git\chatApp\node_modules\mongoose\lib\schematype.js:1210:14)
        at D:\git\chatApp\node_modules\mongoose\lib\document.js:2696:18
        at processTicksAndRejections (node:internal/process/task_queues:78:11) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `email` is required.',
        type: 'required',
        path: 'email',
        value: undefined
      },
      kind: 'required',
      path: 'email',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'message validation failed'
}
```

**Comment by ankitgarg1234** [comment]
yep sure

**Pull request merged**
